
STARTINGCASH = 100000
CURRENTCASH = STARTINGCASH
NETWORTH = CURRENTCASH
DIVERSIFICATION = 10
ASSETS = []

def getTotalReturns():
	return (CURRENTCASH/STARTINGCASH-1)*100

def getDiversifiedCash():
	return (NETWORTH/DIVERSIFICATION)

def 